import type { BitableTableDef } from '@shared/api.interface';

export const BITABLE_TABLES: BitableTableDef[] = [
  {
    tableKey: 'outreach',
    tableId: 'tblXXXXXXXXXXXXXX01',
    name: '触达记录表',
    fields: [
      { key: 'platform', label: '平台', type: 'select', options: ['B站', '知乎', '即刻', '小红书', '抖音', '公众号', '快手', 'GitHub', 'Reddit', 'X(Twitter)', 'V2EX', 'YouTube', 'Hacker News', '微信群', '其他'], required: true },
      { key: 'targetNickname', label: '对方昵称/ID', type: 'text', required: true },
      { key: 'targetProfileUrl', label: '对方主页链接', type: 'text' },
      { key: 'scriptUsed', label: '使用话术（简述）', type: 'textarea' },
      { key: 'outreachType', label: '触达类型', type: 'select', options: ['常规触达', '重点邀约'], required: true },
      { key: 'result', label: '结果', type: 'select', options: ['已发送', '已回复', '已注册', '已发布内容', '拒绝', '无回应'], required: true },
      { key: 'outreachDate', label: '触达日期', type: 'date', autoFill: 'today', required: true },
      { key: 'lastFollowUpTime', label: '最近跟进时间', type: 'date' },
      { key: 'follower', label: '跟进人', type: 'text', autoFill: 'internName', required: true },
      { key: 'remarks', label: '备注', type: 'textarea' },
    ],
  },
  {
    tableKey: 'interview',
    tableId: 'tblXXXXXXXXXXXXXX02',
    name: '访谈记录表',
    fields: [
      { key: 'interviewTitle', label: '访谈标题（一句话概括）', type: 'text', required: true },
      { key: 'interviewDate', label: '访谈日期', type: 'date', autoFill: 'today', required: true },
      { key: 'intervieweeNickname', label: '被访谈人昵称/ID', type: 'text', required: true },
      { key: 'intervieweeIdentity', label: '被访谈人身份', type: 'select', options: ['已注册未发布', '已发布创作者', '触达未注册', '流失用户', '其他'], required: true },
      { key: 'interviewMethod', label: '访谈方式', type: 'select', options: ['私信文字', '语音通话', '视频通话', '问卷', '其他'] },
      { key: 'interviewType', label: '访谈类型', type: 'select', options: ['入驻邀约回访', '流失原因调研', '需求挖掘', '使用体验反馈', '其他'] },
      { key: 'platform', label: '平台', type: 'select', options: ['B站', '知乎', '即刻', '小红书', '抖音', '公众号', '微信群', '其他'] },
      { key: 'relatedOutreach', label: '关联触达记录（对方昵称）', type: 'text' },
      { key: 'interviewSummary', label: '访谈内容摘要（关键问答）', type: 'textarea', required: true },
      { key: 'keyFindings', label: '关键发现/痛点', type: 'textarea' },
      { key: 'followUpActions', label: '后续动作', type: 'textarea' },
      { key: 'interviewer', label: '访谈人', type: 'text', autoFill: 'internName', required: true },
      { key: 'interviewerRemarks', label: '访谈人备注', type: 'textarea' },
    ],
  },
  {
    tableKey: 'viral_candidates',
    tableId: 'tblXXXXXXXXXXXXXX03',
    name: '爆款候选池',
    fields: [
      { key: 'contentTitle', label: '内容标题/简述', type: 'text', required: true },
      { key: 'contentType', label: '类型', type: 'select', options: ['Prompt', 'Skill', '工具', '教程', '其他'], required: true },
      { key: 'sourcePlatform', label: '来源平台', type: 'select', options: ['B站', '知乎', '即刻', '小红书', '抖音', 'GitHub', 'Reddit', 'X(Twitter)', 'V2EX', 'Hacker News', '微信群', '其他'], required: true },
      { key: 'sourceLink', label: '来源链接', type: 'text', required: true },
      { key: 'popularity', label: '热度（点赞/评论/星标数）', type: 'text' },
      { key: 'problemSolved', label: '解决什么问题', type: 'textarea' },
      { key: 'discoveryDate', label: '挖掘日期', type: 'date', autoFill: 'today', required: true },
      { key: 'discoverer', label: '挖掘人', type: 'text', autoFill: 'internName', required: true },
      { key: 'testedStatus', label: '是否测试', type: 'select', options: ['待测试', '已测试', '已淘汰'] },
      { key: 'testScore', label: '测试评分（满分20）', type: 'number' },
      { key: 'testEvaluation', label: '测试效果评价', type: 'textarea' },
      { key: 'sharedInGroup', label: '是否入群分享', type: 'select', options: ['未分享', '已分享'] },
      { key: 'distributedOnPlatform', label: '是否分发平台', type: 'select', options: ['未分发', '已分发'] },
      { key: 'remarks', label: '备注', type: 'textarea' },
    ],
  },
  {
    tableKey: 'community_feedback',
    tableId: 'tblXXXXXXXXXXXXXX04',
    name: '社群反馈表',
    fields: [
      { key: 'feedbackNickname', label: '反馈人昵称', type: 'text', required: true },
      { key: 'feedbackType', label: '反馈类型', type: 'select', options: ['Bug/报错', '产品建议', '使用提问', '内容需求', '表扬/正面', '情绪宣泄', '其他'], required: true },
      { key: 'feedbackContent', label: '反馈内容', type: 'textarea', required: true },
      { key: 'feedbackDate', label: '反馈日期', type: 'date', autoFill: 'today', required: true },
      { key: 'recorder', label: '记录人', type: 'text', autoFill: 'internName', required: true },
      { key: 'processingStatus', label: '处理状态', type: 'select', options: ['待处理', '处理中', '已闭环'] },
      { key: 'processingMethod', label: '处理方式', type: 'select', options: ['已回复', '转E线bug台账', '转D线选题', '私聊安抚', '上报mentor', '待处理'] },
      { key: 'remarks', label: '备注', type: 'textarea' },
    ],
  },
  {
    tableKey: 'content_distribution',
    tableId: 'tblXXXXXXXXXXXXXX05',
    name: '内容分发清单',
    fields: [
      { key: 'contentNumber', label: '内容编号', type: 'text' },
      { key: 'contentTitle', label: '内容标题', type: 'text', required: true },
      { key: 'contentType', label: '内容类型', type: 'select', options: ['Prompt', 'Skill', '测评帖', '爆款改写', '其他'], required: true },
      { key: 'distributionPlatform', label: '分发平台', type: 'select', options: ['B站', '知乎', '小红书', '抖音', '公众号', '快手', '其他'], required: true },
      { key: 'distributor', label: '分发人', type: 'text', autoFill: 'internName', required: true },
      { key: 'publishDate', label: '发布日期', type: 'date', autoFill: 'today', required: true },
      { key: 'publishStatus', label: '发布状态', type: 'select', options: ['待发布', '已发布', '发布失败'] },
      { key: 'publishLink', label: '发布链接', type: 'text' },
      { key: 'remarks', label: '备注', type: 'textarea' },
    ],
  },
  {
    tableKey: 'topic_scheduling',
    tableId: 'tblXXXXXXXXXXXXXX06',
    name: '选题排产表',
    fields: [
      { key: 'topicTitle', label: '选题标题', type: 'text', required: true },
      { key: 'contentType', label: '内容类型', type: 'select', options: ['Prompt（人投）', 'Prompt（机投）', 'Skill', '测评帖'], required: true },
      { key: 'topicCategory', label: '题材', type: 'select', options: ['效率办公', '编程开发', '写作创作', '学习教育', '生活日常', '数据分析', '设计创意', '其他'] },
      { key: 'source', label: '来源', type: 'select', options: ['挖掘需求文档', 'C线爆款池', '用户反馈', '自己想的', '其他'] },
      { key: 'priority', label: '优先级', type: 'select', options: ['高', '中', '低'] },
      { key: 'responsiblePerson', label: '负责人', type: 'text', autoFill: 'internName', required: true },
      { key: 'plannedDate', label: '计划日期', type: 'date', autoFill: 'today' },
      { key: 'status', label: '状态', type: 'select', options: ['待排产', '排产中', '已发布', '已降权'] },
      { key: 'publishDate', label: '发布日期', type: 'date' },
      { key: 'publishLink', label: '发布链接', type: 'text' },
      { key: 'copyCount', label: '复制数', type: 'number' },
      { key: 'runCount', label: '运行数', type: 'number' },
      { key: 'likeCount', label: '点赞数', type: 'number' },
      { key: 'remarks', label: '备注', type: 'textarea' },
    ],
  },
  {
    tableKey: 'daily_checkin',
    tableId: 'tblXXXXXXXXXXXXXX07',
    name: '每日打卡记录',
    fields: [
      { key: 'date', label: '日期', type: 'date', required: true },
      { key: 'internName', label: '实习生姓名', type: 'text', required: true },
      { key: 'direction', label: '方向', type: 'select', options: ['A触达与邀约', 'B官方账号', 'C社群与爆款', 'D供给线', 'E情报与产品', '公共任务'], required: true },
      { key: 'recordTitle', label: '记录标题', type: 'text' },
      { key: 'taskAction', label: '任务动作', type: 'text' },
      { key: 'dailyGoal', label: '当日目标（做多少）', type: 'text' },
      { key: 'actualCompletion', label: '实际完成量（数字说话）', type: 'text' },
      { key: 'completed', label: '是否完成', type: 'checkbox' },
      { key: 'outputLinks', label: '产出物链接', type: 'text' },
      { key: 'backfillTable', label: '回填到哪张表', type: 'select', options: ['触达记录表', '访谈记录表', '爆款候选池', '社群反馈表', '内容分发清单', '选题排产表', 'bug台账（外部表）', '功能提案表（外部表）', '平台数据表', '不用回填'] },
      { key: 'northStarMetric', label: '对应北极星指标', type: 'text' },
      { key: 'blockers', label: '卡点/备注', type: 'text' },
      { key: 'mentorStatus', label: 'mentor验收', type: 'select', options: ['待验收', '通过', '需改进'] },
      { key: 'mentorFeedback', label: 'mentor反馈', type: 'text' },
    ],
  },
];
